server:
  port: 8081

spring:
  application:
    name: AdminPanel

  datasource:
    url: jdbc:postgresql://localhost/admin_panel
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none