--liquibase formatted sql
--changeset osipova.va:init failOnError:True dbms:postgresql

create table if not exists city
(
    id bigint generated by default as identity
        constraint city_pkey
            primary key,
    name varchar(15) not null
);

create table if not exists users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    first_name varchar(15) not null,
    last_name varchar(15) not null,
    patronymic varchar(15),
    birth_date date not null,
    email varchar(50) not null,
    phone varchar(11) not null,
    password varchar(255) not null,
    city_id int not null references city (id),
    registration_date date not null
);

create table if not exists role
(
    id bigint generated by default as identity
        constraint role_pkey
            primary key,
    name varchar(15) not null
);

create table user_roles(
    user_id int not null references users(id),
    role_id int not null references role(id),

    unique (user_id, role_id)
);

create table course(
    id bigint generated by default as identity
        constraint course_pkey
            primary key,
    name varchar(100) not null,
    description text not null,
    price money not null
);

create table course_program(
    id bigint generated by default as identity
        constraint course_program_pkey
            primary key,
    course_id int not null references course(id),
    is_actual boolean not null,
    title varchar(50) not null
);

create table "group"(
    id bigint generated by default as identity
        constraint group_pkey
            primary key,
    start_date date not null,
    end_date date not null,
    time_start time(0) not null,
    duration int not null,
    course_program_id int not null references course_program(id)
);

create table news(
    id bigint generated by default as identity
        constraint news_pkey
                 primary key,
    title varchar(50) not null,
    content text not null,
    publication_date date not null,
    author_id int not null references users(id),
    recipient_id int references users(id),
    group_id int references "group"(id)
);

create table program_details(
    id bigint generated by default as identity
        constraint program_details_pkey
                            primary key,
    course_program_id int not null references course_program(id),
    lesson_number int not null,
    lesson_theme varchar(100) not null
);

create table theme_details(
    id bigint generated by default as identity
        constraint theme_details_pkey
                          primary key,
    program_details_id int not null references program_details(id),
    topic varchar(100) not null
);

create table course_program_skill(
    id bigint generated by default as identity
        constraint course_program_skill_pkey
            primary key,
    course_program_id int not null references course_program(id),
    name varchar(50) not null
);

create table user_skill(
    users_id int not null references users(id),
    course_program_skill_id int not null references course_program_skill(id),

    unique (users_id, course_program_skill_id)
);

create table attestation_theme(
    id bigint generated by default as identity
        constraint attestation_theme_pkey
            primary key,
    course_id int not null references course(id),
    theme varchar(50) not null
);

create table user_attestation(
    id bigint generated by default as identity
         constraint user_attestation_pkey
             primary key,
    users_id int not null references users(id),
    attestation_theme_id int not null references attestation_theme(id),
    theory_passed boolean not null,
    practice_passed boolean not null
);

create table lesson(
    id bigint generated by default as identity
        constraint lesson_pkey
            primary key,
    group_id int not null references "group"(id),
    day date not null,
    home_task varchar(200),
    read varchar(100),
    videos varchar(100)
);

create table lesson_topic(
    lesson_id int not null references lesson(id),
    theme_details_id int not null references theme_details(id),

    unique (lesson_id, theme_details_id)
);

create table student_group(
    id bigint generated by default as identity
        constraint student_group_pkey
            primary key,
    users_id int not null references users(id),
    group_id int not null references "group"(id),
    rating int
);

create table time_table(
    id bigint generated by default as identity
        constraint time_table_pkey
            primary key,
    group_id int not null references "group"(id),
    room_number int not null,
    day date not null,
    time_start time(0) not null,
    time_end time(0) not null
);

create table journal(
    id bigint generated by default as identity
        constraint journal_pkey
            primary key,
    users_id int not null references users(id),
    lesson_id int not null references lesson(id),
    absent boolean not null,
    absent_reason varchar(50),
    feadback text
)
